site_name: ğŸª Code && Media Art
nav:
  - ğŸ“‹Syllabus: index.md
  - ğŸ“†Schedule: schedule.md
  - ğŸ’»Notes:
    - Notes Index: notes/notes.md
    - 0. Playing with Code(s): 00_procedural_experiments.md
    - 1. Shape && Color: 01_p5.md
    - 0. Variables && Random: 02_variables.md
  - ğŸ“šExercises:
    - Exercises Index: exercises/exercises.md
    - In-Class:
      - 0. Conditional Drawing: exercises/00_conditiondrawing.md
      - 1a. Drawing: exercises/01_Drawing.md
      - 1b. Drawing in Color: exercises/01_drawingincolor.md
      - 2a. Painting Program: exercises/02_paint.md
      - 2b. Random Dots: exercises/02_dots.md 
    - Independent:
      - 1. p5!: exercises/00_signup.md
      - 2. Light and Color: exercises/01_LightandColor.md
      - 3. Face Generator: exercises/02_face.md
  - ğŸŒProjects:
    - Time: time.md
    - Narrative: narrative.md
    - Performance: performance.md
    - Game Ring: game.md
  - ğŸ“–Responses:
    - Art && Technology: art.md
    - Culture && Ideology: culture.md
    - Power && Surveillance: power.md
    - Play && Internet: play.md
  - ğŸ–ï¸Artists:
    - Casey Reas: artists/01_caseyreas.md
    - Lauren Lee McCarthy: artists/02_laurenmccarthy.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: On this page
      toc_depth: 2

theme:
  favicon: ampersand.svg
  icon:
    logo: material/ampersand
  name: material
  highlightjs: true
  palette:
    scheme: default
    primary: white
    accent: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant: false
  font:
    text: Funnel Sans
    code: Inconsolata monospace
plugins:
  - search:
      enabled: true


extra_css:
- extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"